name: Deploy App

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci

      - name: Build app
        run: npm run build

      - name: Upload and deploy on server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: 22
          source: "deploy.zip"
          target: "${{ vars.DEPLOY_PATH }}/deploy.zip"
          script: |
            cd ${{ vars.DEPLOY_PATH }}

            # Unzip the deployment
            unzip -o deploy.zip
            rm deploy.zip

            # Create config.php using GitHub secrets
            cat <<EOF > config.php
<?php

\$servername = '${{ secrets.DB_SERVER }}';
\$username = '${{ secrets.DB_USER }}';
\$password = '${{ secrets.DB_PASSWD }}';
\$dbname = '${{ secrets.DB_NAME }}';

\$secretkey = '${{ secrets.SECRET_KEY }}';

\$authusers = [
    "kyle" => '${{ secrets.USER_KYLE }}',
    "lexie" => '${{ secrets.USER_LEXIE }}'
];

?>
EOF
